project-id="dev-project-345909"
sqldb-inst-name="sqldb103"
sqldb-region="asia-southeast1"
sqldb-name="wpdb"
sqldbpass="sql-wp@&A#"
gke-cluster-name="wp-gke-cluster"
gke-region="us-central1-c"
gke-node-name="wp-node-pool"
